const $=id=>document.getElementById(id); const state={assets:[],cards:[],activeCard:null,openCard:null,draft:'kinky-tcg-level-builder'}; const rarities=['Coquine','Provocante','Audacieuse','Envoûtante','Sulfureuse','Mythique']; const cardTypes=['Accessoire','Action','Lieu','Position','Rituel','Tenue'];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const slug=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const metaFields=['themeId','themeName','themeDescription','difficulty','seal'];
  function toast(text){const n=$('toast');n.textContent=text;n.classList.add('show');clearTimeout(window.toast);window.toast=setTimeout(()=>n.classList.remove('show'),2500)}
  function blank(source={},custom=false){return {id:source.id||Date.now()+Math.floor(Math.random()*1000),type:source.type||'Action',passwordHash:source.passwordHash||'',password:source.password||'',hints:Array.isArray(source.hints)?source.hints:[source.hint||''],title:source.title|| (custom?'Nouvelle carte':'Carte'),image:source.image||'',description:source.description||'',actions:source.actions||'',rarity:source.rarity||'Coquine'}}
  function readMeta(){return {id:$('themeId').value.trim(),name:$('themeName').value.trim(),description:$('themeDescription').value.trim(),difficulty:$('difficulty').value,seal:$('seal').value.trim()}}
  function setMeta(t={}){if(t.id!==undefined)$('themeId').value=t.id;if(t.name!==undefined)$('themeName').value=t.name;if(t.description!==undefined)$('themeDescription').value=t.description;if(t.difficulty)$('difficulty').value=t.difficulty;if(t.seal!==undefined)$('seal').value=t.seal}
  function renderAssets(){const term=$('assetSearch').value.toLowerCase();const list=state.assets.filter(a=>`${a.name} ${a.category} ${a.path}`.toLowerCase().includes(term));$('assetGrid').innerHTML=list.map(a=>`<button class="asset-tile" data-asset="${esc(a.path)}" title="${esc(a.path)}"><img src="${esc(a.path)}" alt=""><span>${esc(a.name)}</span></button>`).join('')||'<p class="builder-note">Aucune image.</p>'}
  function renderCards(){ $('emptyState').style.display=state.cards.length?'none':'block'; if(state.openCard===null && state.cards.length) state.openCard=state.cards.length-1; $('stepsList').innerHTML=state.cards.map((c,i)=>`<article class="step-card${state.openCard===i?'':' collapsed'}" data-index="${i}"><header class="step-head" aria-expanded="${state.openCard===i}"><span class="step-index">${String(i+1).padStart(2,'0')}</span><img class="step-thumb" src="${esc(c.image||'assets/ico/trading-card.png')}" alt=""><strong>${esc(c.title)}</strong><button class="btn btn-sm btn-builder-outline" data-action="up">↑</button><button class="btn btn-sm btn-builder-outline" data-action="down">↓</button><button class="btn btn-sm btn-builder-outline" data-action="remove">×</button></header><div class="step-body"><div class="builder-grid"><div class="builder-field"><label>Titre *</label><input data-field="title" value="${esc(c.title)}"></div><div class="builder-field"><label>Type</label><select data-field="type">${cardTypes.map(type=>`<option value="${esc(type)}"${type===c.type?' selected':''}>${esc(type)}</option>`).join('')}</select></div><div class="builder-field"><label>Mot(s) de passe / réponse *</label><input data-field="password" value="${esc(c.password)}" placeholder="réponse | variante"></div><div class="builder-field"><label>Rareté</label><select data-field="rarity">${rarities.map(r=>`<option value="${esc(r)}"${r===c.rarity?' selected':''}>${esc(r)}</option>`).join('')}</select></div><div class="builder-field builder-full"><label>Énigmes / indices (une ligne par indice)</label><textarea data-field="hints">${esc(c.hints.join('\n'))}</textarea></div><div class="builder-field builder-full"><label>Image</label><input data-field="image" value="${esc(c.image)}" placeholder="assets/cartes/Actions/…"></div><div class="builder-field builder-full"><label>Description</label><textarea data-field="description">${esc(c.description)}</textarea></div><div class="builder-field builder-full"><label>Action / réponse révélée</label><textarea data-field="actions">${esc(c.actions)}</textarea></div></div></div></article>`).join('');update()}
  function sync(el,field,value){const i=+el.closest('.step-card').dataset.index;if(field==='hints')state.cards[i].hints=value.split('\n').map(x=>x.trim()).filter(Boolean);else if(field==='password')state.cards[i].password=value;else state.cards[i][field]=value;update()}
  async function sha(v){const data=new TextEncoder().encode(v.trim().toLowerCase());const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  async function exportData(){const m=readMeta();return {themes:[{id:m.id||slug(m.name)||'nouveau-theme',name:m.name||'Nouveau thème',description:m.description,difficulty:m.difficulty,seal:m.seal,cards:await Promise.all(state.cards.map(async c=>{const answers=c.password.split('|').map(x=>x.trim()).filter(Boolean);return {id:Number(c.id)||c.id,type:c.type,passwordHash:answers[0]?await sha(answers[0]):c.passwordHash,hints:c.hints,title:c.title,image:c.image,description:c.description,actions:c.actions,rarity:c.rarity}}))}]}}
  async function update(){const data=await exportData();$('jsonPreview').value=JSON.stringify(data,null,2);$('cardCount').textContent=state.cards.length;$('hintCount').textContent=state.cards.reduce((n,c)=>n+c.hints.length,0);const ready=state.cards.length&&state.cards.every(c=>c.title&&c.password&&c.hints.length&&c.image);$('readyCount').textContent=(ready?100:Math.round(state.cards.filter(c=>c.title&&c.password&&c.hints.length&&c.image).length/Math.max(1,state.cards.length)*100))+'%'}
  function add(source,custom=false){state.openCard=state.cards.length;state.cards.push(blank(source,custom));renderCards();$('stepsList').lastElementChild?.scrollIntoView({behavior:'smooth',block:'center'})}
  $('assetSearch').oninput=renderAssets;metaFields.forEach(id=>$(id).addEventListener('input',update));
  $('stepsList').addEventListener('input',e=>{if(e.target.dataset.field)sync(e.target,e.target.dataset.field,e.target.value)});$('stepsList').addEventListener('click',e=>{const row=e.target.closest('.step-card');if(!row)return;const action=e.target.dataset.action;if(!action){if(e.target.closest('.step-head')){const index=+row.dataset.index;state.openCard=state.openCard===index?null:index;renderCards();}return;}const i=+e.target.closest('.step-card').dataset.index;if(action==='remove')state.cards.splice(i,1);if(action==='up'&&i) [state.cards[i-1],state.cards[i]]=[state.cards[i],state.cards[i-1]];if(action==='down'&&i<state.cards.length-1)[state.cards[i],state.cards[i+1]]=[state.cards[i+1],state.cards[i]];renderCards()});
  $('assetGrid').addEventListener('click',e=>{const tile=e.target.closest('[data-asset]');if(!tile){return}const card=state.activeCard??state.cards.length-1;if(card<0){toast('Ajoutez d’abord une carte.');return}state.cards[card].image=tile.dataset.asset;renderCards();toast('Image appliquée à la carte.')});$('stepsList').addEventListener('focusin',e=>{const row=e.target.closest('.step-card');if(row)state.activeCard=+row.dataset.index});
  $('addCustomBtn').onclick=()=>add({},true);
  $('downloadBtn').onclick=async()=>{const data=await exportData(),text=JSON.stringify(data,null,2),blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${data.themes[0].id}.json`;a.click();URL.revokeObjectURL(url);toast('Thème JSON téléchargé.')};$('copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('jsonPreview').value);toast('JSON copié.')};$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text()),t=data.themes?.[0];if(!t)throw Error();setMeta(t);state.cards=(t.cards||[]).map(c=>blank(c));renderCards();toast('Thème importé.')}catch(err){toast('JSON invalide : le fichier doit contenir themes[].')}e.target.value=''};
  fetch('assets/cartes/index.json').then(r=>r.json()).then(assets=>{state.assets=assets;renderAssets()}).catch(()=>toast('Impossible de charger les images locales.'));renderCards();
